type User {
id: String!
name: String!
email: String!
password: String!
}
type Device{
    id: String!
    userid: String !
    name:String!
    type:String!
    serialNumber:String!
    status:String!
}
type Query {
user(id: String!): User
users: [User!]!
devicesByUserID(userid: String!): [Device!]!
devices: [Device!]!
}
type Mutation {
addUser(name: String!, email: String!, password: String!): User
updateUser(id: String!, name: String!, email: String!, password: String!): User
deleteUser(id: String!): Boolean!
addDevice(userid: String!, name: String!, type: String!, serialNumber: String!, status: String!): Device
updateDevice(id:String!,name:String!,type:String!,serialNumber:String!,status:String!):Device
deleteDevice(id:String!):Boolean!

}
